[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
anstyle = "0.3.5"
anyhow = "1.0.70"
clap = { version = "4.1.14", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
tokio = { version = "1.26.0", features = ["full"] }